### ISSUE TITLE
1_move_files.py doe not work?

### ISSUE THREAD

**Issue by yokings** [sujiongming/UCF-101_video_classification#1]

**Comment by sujiongming** [comment]
make sure images in the data dir
follow the command
cd data && wget http://crcv.ucf.edu/data/UCF101/UCF101.rar

Then extract it with unrar e UCF101.rar.

Next, create folders (still in the data folder) with mkdir train && mkdir test && mkdir sequences && mkdir checkpoints.

I run it at ubuntu 16.04 without problems.
good luck

**Comment by yokings** [comment]
Thanks,I have solved it,it’s been right
